### PR TITLE
Added project PseudoTube

### PR DESCRIPTION
**Pull request by MaksimPir**
## Background
Added my own project PseudoTube, it is an example of project where using FSD

## Changelog

Added in /pages/examples/img/pseudoTube_screens.png
Added  in /pages/examples/config

### CODE REVIEW

**Comment by illright** [comment]
Hey, thanks for the example! Didn't review the code yet, will do soon, but I have some preliminary comments in the meantime:
1. Could you delete the `.vs` folder from your PR please?
2. I see in your GitHub that you have a link to the preview, could you also add that?

**Comment by MaksimPir** [comment]
Hi! Added commit, please check it.

**Comment by illright** [comment]
I checked out the code and the architectural part feels pretty solid, but I'm really not a fan of the website design, namely, the colors. Could you change that?

**Comment by MaksimPir** [comment]
Hm... I think colors and design are subjective for everyone. In my opinion, this case suggests an example for learning how to use FSD in practice, and not about a beautiful web interface. The colors I chose for my application are not so ugly and do not hurt the eyes of users. If you can tell me the colors I should use, then I will change them

**Comment by illright** [comment]
Consider the visual style of well-established component libraries such as MUI, Ant Design, Carbon, etc. They often have a white background with high-contrast text and sparse use of accent colors.

**Comment by illright** [comment]
Closing this as stale

**Pull request closed without merging**
