### PR TITLE
Add new example

### PR DESCRIPTION
**Pull request by sanua356**
Hello everyone! I suggest adding a mini-game to the documentation, since there are currently no projects in the game development area. The linter "staiger" was launched before the creation of the PR, no errors were found.

Game repository: https://github.com/sanua356/tiny-bunny
View demo: https://sanua356.github.io/tiny-bunny/

### CODE REVIEW

**Comment by illright** [comment]
Hey, thanks for the example, looks really cool! I noticed that you have a typo in the folder name "entities", that could lead Steiger to miss some files, could you fix it and run the linter again please?

**Comment by sanua356** [comment]
@illright 
Yes. I renamed the entities folder to the correct type and fixed a small number of new errors in "steiger" after the renaming. The linter now reports no errors.
image

**Comment by illright** [comment]
I'm a bit unsure about the `hatchButtons` entity. It's just a UI component without any business logic, so I'd suggest putting it in `shared/ui` instead. The rest is pretty good!

**Comment by sanua356** [comment]
I agree. Earlier, when the prototype of the application was just emerging, this component contained logic, so it was on this layer. I have already transferred it to "shared/ui". I launched the linter, no errors appeared.

**Comment by illright** [comment]
Could you please move your example from the first position in the array of examples to the last? Otherwise it appears at the end of the list, not in the beginning

**Comment by sanua356** [comment]
Okay. No problem. 3 minutes.

**Comment by sanua356** [comment]
Done

**Review by illright — APPROVED** [review]
Thanks!

**Pull request merged**
