### PR TITLE
Add new example: Kanban task management app

### PR DESCRIPTION
**Pull request by Un1T3G**

### CODE REVIEW

**Comment by Un1T3G** [comment]
Add new example: Kanban task management

**Review by Un1T3G — COMMENTED** [review]
.

**Review by illright — CHANGES_REQUESTED** [review]
I noticed some FSD violations by running our linter:
```
pnpm dlx steiger ./src
```

Could you address them please?

**Comment by illright** [comment]
This PR has gone stale, so I'll close it, but feel free to re-open if you still want to add this example

**Pull request closed without merging**
