### PR TITLE
fix(docs): Corrects incorrect URLs to Sergey Sova's site

### PR DESCRIPTION
**Pull request by AntonAmbarov**
Past url invalid https://sova.dev/ru/why-utils-and-helpers-is-a-dump/

### CODE REVIEW

**Comment by illright** [comment]
Thanks! Sergey Sova has a new domain, so we can actually change the link to the Russian version: https://sergeysova.com/ru/why-utils-and-helpers-is-a-dump/

Could you also replace other references to sova.dev in the project with sergeysova.com please?

**Comment by sanua356** [comment]
@illright Hello. Can you take a look at pull request #711 ? I changed the structure of the article about a month ago, but it remained without review.

**Comment by AntonAmbarov** [comment]
> Thanks! Sergey Sova has a new domain, so we can actually change the link to the Russian version: https://sergeysova.com/ru/why-utils-and-helpers-is-a-dump/
> 
> Could you also replace other references to sova.dev in the project with sergeysova.com please?

Yeah, no problem

**Comment by AntonAmbarov** [comment]
@illright I replaced the domain sova.dev with sergeysova.com

**Review by illright — APPROVED** [review]
Thank you!

**Pull request merged**
