### PR TITLE
feat: translate get-started folder index, overview to Korean

### PR DESCRIPTION
**Pull request by movie42**
Hello.
I've been applying FSD to my project recently. FSD has been very helpful to me.
In particular, I had experience with dependencies becoming entangled in previous projects, and I think the biggest advantage of FSD might be its ability to isolate business logic.

## Background

While studying, I thought I'd like to contribute by translating the documentation into Korean.
This translation was completed with the assistance of AI. However, I personally reviewed it, refining or paraphrasing parts that were too literal, unnatural, or unclear in conveying the intended meaning. Throughout the translation, I avoided using slang and maintained formal expressions.

## Changelog

- add flag kr in i18n.js
- add scripts kr in package.json
- translate get-started index file to kr
- translate overview to kr

스크린샷 2024-08-30 오전 10 36 01

### CODE REVIEW

**Comment by illright** [comment]
Hi, thanks a lot! Translating the docs is super important, I'm very glad that you took on this. I'll review it to the best of my abilities

**Comment by illright** [comment]
I looked over it, seems nice, the only thing is the home page has missing strings. Could you fill those in as well?

https://deploy-preview-715--pr-fsd.netlify.app/kr/

image

**Comment by movie42** [comment]
Thank you for the review. 

I confirmed that the broken part was also visible in local development, and I added code.json to fix it. 

However, I couldn't verify the fix in the Netlify preview. It seems that the commit I made hasn't been deployed.

I went through all the pages to check if there were any other broken parts, but compared to the deployed pages, it looks like there aren't any other broken sections.

**Review by illright — APPROVED** [review]
Thanks! Would you like to have a Korean-language thread in our Telegram chat, by the way?

**Comment by movie42** [comment]
Thank you. 
But This doesn't represent the opinion of all Koreans, but Telegram has somewhat lower utility in Korea. I know there's a Discord channel, so could you create a Korean language channel there?

**Pull request merged**
